
# @name login
POST http://localhost:8443/realms/fc3-codeflix/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=fc3-admin-do-catalogo
&client_secret=**********
&grant_type=password
&username=joaotavioos
&password=123456


###

@authToken = {{login.response.body.access_token}}
@refreshToken = {{login.response.body.refresh_token}}

GET http://localhost:8080/api/categories
Authorization: Bearer  {{authToken}}